### ISSUE TITLE
error: logger: SampleRNNLogger ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Jazmin7** [davidalvarezdlt/samplernn_pase#3]
Hi， 
I encountered an error.
logger: SampleRNNLogger
          ^
SyntaxError: invalid syntax

Can you tell me why it is happened?
Thank you!

**Comment by davidalvarezdlt** [comment]
Jazmin, I've used the Typing feature of Python (check PEP 484), which is available starting from Python 3.5. The code has been tested in Python 3.6 and 3.7.

Anyways, I will remove the typing in a future refactoring of the code.
